### ISSUE TITLE
Add 0.6.1 tag

### ISSUE THREAD

**Issue by beriain** [zoenb/log28#4]
Hi! In the commit  606e095 you bumped the version to 0.6.1 but, as you haven't added a [tag](https://github.com/zoenb/log28/tags), there has not been an update of your app in [F-Droid](https://f-droid.org/packages/com.log28). Could you please add a tag so the latest changes can reach F-Droid too and not only Google's Play Store?

Thank you very much.

**Comment by zoenb** [comment]
done!
